#!/usr/bin/env python3

"""Script to retreve datasets (input or output) in submitted jobs

With a specified search string, will search for datasets with that
name. If the name doesn't end in `*` or `/`, append a wildcard.
Without a specified search string, the datasets can be piped.

The user name can be specified via environment variable to reduce
clutter.

"""
# help strings
_h_taskname='initial search string'
_h_user='full user name, or blank for all'
_h_stream='stream name fragment to filter for'
_h_days='only look back this many days'
_h_state='prefix dataset name with state'
# defaults
_def_user='GRID_USER_NAME'
_def_stream='OUT'

from urllib import request, parse
import json
import sys, os
import re
import argparse

_headers = {'Accept': 'application/json',
            'Content-Type':'application/json',
            'User-Agent':'User-Agent: curl/7.43.0'}

def get_args():
    d = ' (default: %(default)s)'
    c = ' (default: %(const)s)'
    user=os.environ.get(_def_user, '')
    if not user:
        de = ' (please set {} environment variable)'.format(_def_user)
    else:
        de = d
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('taskname', help=_h_taskname, nargs='?')
    parser.add_argument('-u','--user', help=_h_user + de, default=user)
    parser.add_argument('-d','--days', help=_h_days, type=int)
    addinfo = parser.add_mutually_exclusive_group()
    addinfo.add_argument('-s','--stream', help=_h_stream + c, nargs='?',
                         default=None, const=_def_stream)
    args = parser.parse_args()
    if not args.taskname and sys.stdin.isatty():
        parser.print_usage()
        sys.exit('ERROR: need to pipe datasets or specify a search string')
    return args

def get_datasets(taskname, user, days=None):
    pars = {
        'taskname': taskname,
        'username': user,
    }
    if days is not None:
        pars['days'] = days
    url = 'http://bigpanda.cern.ch/tasks/?' + parse.urlencode(pars)
    req = request.Request(url, headers=_headers)
    return json.loads(request.urlopen(req).read().decode('utf-8'))

def get_ds(taskid, streamfrag):
    params = parse.urlencode({'jeditaskid': taskid})
    url = 'http://bigpanda.cern.ch/tasks/?' + params
    req = request.Request(url, headers=_headers)
    stuff = request.urlopen(req).read().decode('utf-8')
    # containers = set()
    for entry in json.loads(stuff):
        datasets = entry['datasets']
        streams = {ds['streamname']: ds for ds in datasets}
        for stream, ds in streams.items():
            if streamfrag.upper() in stream:
                yield streams[stream]['containername']


RED = '\033[0;91m'
GREEN = '\033[92m'
YELLOW = '\033[93m'
BLUE = '\033[94m'
MAGENTA = '\033[95m'
CYAN = '\033[96m'
ENDC = '\033[0m'
BOLD = '\033[1m'
UNDERLINE = '\033[4m'
BLINK = '\033[5m'

_color_dic = {
    'running': BLUE + BOLD,
    'submitting': CYAN,
    'registered': MAGENTA,
    'ready': MAGENTA,
    'done': GREEN,
    'finished': YELLOW,
    'broken': RED + BOLD,
    'aborted': RED,
    'failed': RED,
    }
def getstatus(task):
    if sys.stdout.isatty():
        color = _color_dic.get(task['superstatus'], ENDC)
        status_color = color + task['status'] + ENDC
        nonprlen = len(color) + len(ENDC)
    else:
        status_color = task['status']
        nonprlen = 0

    return '{s:<{l}} {i:<9} {t}'.format(
        s=status_color, t=task['taskname'], i=task['reqid'],
        l=(11 + nonprlen))

def stdin_iter(args):
    for line in sys.stdin:
        yield from get_datasets(line.strip(), args.user, args.days)

def run():
    args = get_args()

    taskname = args.taskname
    # try to search
    if taskname is not None:
        # append a wildcard if I forgot
        if args.taskname[-1] not in '/*':
            taskname = taskname + '*'
        datasets = get_datasets(taskname, args.user, args.days)
    else:
        # otherwise read from stdin
        datasets = stdin_iter(args)

    # loop over tasks
    for task in datasets:
        if args.stream:
            for ds in get_ds(task['jeditaskid'], args.stream):
                sys.stdout.write(ds + '\n')
        else:
            sys.stdout.write(getstatus(task) + '\n')


if __name__ == '__main__':
    run()
